name: Validate

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate DTDL models
        uses: SmartOperatingBlock/dtdl-validator-action@1.0.0
        with:
          folder: models